# Generated by Django 4.2.4 on 2023-09-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('suscripcion', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('bajada', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('img_destacada', models.ImageField(upload_to='')),
                ('estatus', models.BooleanField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Notas.autor')),
            ],
        ),
    ]
