# Generated by Django 4.2.3 on 2023-09-06 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.template.defaultfilters


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('suscripcion', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Usuarios/imagenes')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_autor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('bajada', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('img_destacada', models.ImageField(upload_to='')),
                ('estatus', models.BooleanField()),
                ('url', models.URLField(verbose_name=django.template.defaultfilters.slugify)),
                ('autores', models.ManyToManyField(to='Notas.autor')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Notas.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Usuarios/imagenes')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_lector', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
