# Generated by Django 4.2.4 on 2023-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='categoria_nota',
            field=models.ManyToManyField(to='Notas.categoria'),
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
        migrations.AddField(
            model_name='nota',
            name='etiqueta_nota',
            field=models.ManyToManyField(to='Notas.etiqueta'),
        ),
    ]
