# Generated by Django 4.2.4 on 2023-09-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notas', '0002_etiqueta_nota_categoria_nota_delete_lector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='autores',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nombre',
        ),
    ]
